model_selection:
    model:
      logistic_regression:
        penalty: 
          - l1
          - l2
          - elasticnet
        C:
          - 0.5
          - 1
          - 5
        solver: 
          - lbfgs
          - liblinear

      svc:
        kernel:
          - linear
          - poly 
          - rbf
          - sigmoid
        C:
          - 0.1
          - 1
          - 5

      RandomForestClassifier:
        criterion:
          - gini
          - entropy
          - log_loss
        n_estimators:
          - 100
          - 150
          - 200

      GradientBoostClassifier:
        loss:
          - log_loss
          - deviance
          - exponential